// Code generated by go-bindata.
// sources:
// assets/html/home.html
// assets/html/layout.html
// assets/html/navbar.html
// DO NOT EDIT!

package codeye

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _assetsHtmlHomeHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x93\xcd\x6e\x1b\x21\x10\xc7\xef\x7e\x8a\x91\xef\x31\x52\x12\xe5\x50\x91\x95\xaa\xa8\x55\x7b\x68\x4f\x95\x7a\xc6\x86\x5d\x90\x58\xb0\x60\xd6\x71\x85\xf6\xdd\x2b\x3e\xd6\x10\x7b\x9d\x1b\xcc\xfc\x99\x19\x66\x7e\x13\x02\x70\xd1\x2b\x23\x60\x2b\xed\x28\xb6\x30\xcf\x9b\x10\xe0\x5d\xa1\x84\xdd\x77\xe5\x3c\xbe\xd9\x71\x54\x18\xed\x94\xab\x13\x1c\x34\xf3\xfe\x75\xbb\xb7\xe7\x6d\xb7\x01\xa0\xcc\xa1\x3a\x68\xb1\xd8\x47\xc1\x15\x4b\x1e\x80\x56\x9f\xec\x0f\x5a\xf4\x58\x9c\x00\xb4\x57\xc3\xe4\x2e\x2f\xd5\xc8\x06\x01\xca\x3f\xbc\x3c\x9f\x5f\x9e\x2f\x2a\x00\xaa\xc6\x01\xbc\x3b\xbc\x6e\x43\x80\xdd\xd7\x09\xa5\x75\xbb\x9f\x49\x3d\xcf\x35\x1a\xc9\xe1\x4a\x6a\xc2\xd5\xe9\x5e\x15\x07\x6b\x50\x98\xa6\x90\x46\x71\xed\x03\xa0\xc7\x7a\x06\xa0\x1e\x9d\x35\x43\xd7\x94\xf2\x9b\x8d\xb1\x12\x4a\x8a\x0b\xa8\x1f\x99\xd6\xad\xe4\xdb\xc8\x94\xce\x9a\xe4\x5a\x91\xfc\x95\xc2\x34\x8a\x36\xe5\xde\xad\x55\xf0\x83\x79\xf9\xa5\x26\x8d\xa1\xa2\x29\x0e\xea\xee\xdb\x28\xfa\x25\xbc\xcf\xbd\xab\x5f\x24\xc7\xda\xc6\xda\xb8\xe5\x48\x49\x19\x72\xb7\x29\xb6\x10\x40\x18\xfe\x81\x95\x37\x6b\xd0\xa9\xfd\x84\xd6\xf9\x6b\x58\x50\xa1\x16\xa9\xa5\xad\x6a\x09\xb6\xa1\xc8\xf6\x95\xa0\x7c\x51\xfe\xc1\xa3\x53\x47\xc1\xe3\x51\xda\x93\x70\x8b\xbd\x9f\xb4\x7e\x57\x1c\x65\x06\x10\xa5\x60\xbc\x54\x8c\xae\xa3\x28\xbb\x38\x11\x4a\x50\xa6\x4b\xe6\xd7\xe7\x3b\x41\x97\x7f\x54\x5e\xa5\x00\x7b\xcb\xff\xe5\x00\x21\x80\x63\x66\x10\xb0\x2b\xdd\xa1\x78\xe9\x1f\x45\xde\x40\xf1\x09\xf6\xb7\x50\xad\xc0\xff\xf9\x0a\x3c\x3d\x9e\x9f\x1e\xe3\xe1\x38\x69\x2d\xf8\xda\xd3\xeb\xbd\xb8\x59\x88\xb5\xb5\xb8\x99\xf1\xbd\x5a\x6f\xd7\x60\xc1\xa7\xd0\x7e\x3f\x5c\x43\xcb\x62\xa8\x9d\x8b\x4d\x8c\x51\xca\x50\x12\xf0\x8b\x77\x19\x4e\xcc\x23\x0c\x4f\x39\x28\x29\xd3\x49\x83\xea\xad\xc5\x6e\x6d\x2e\x21\x80\x16\x06\x76\x30\xcf\x1f\x10\x5b\x4b\xfd\xc7\x22\xd3\x35\x3f\x54\x3e\xae\xea\xa0\xa4\x24\xa4\x24\x31\x19\xb1\xcf\x75\x55\xfc\xff\x07\x00\x00\xff\xff\xca\x47\x43\x45\x3f\x05\x00\x00")

func assetsHtmlHomeHtmlBytes() ([]byte, error) {
	return bindataRead(
		_assetsHtmlHomeHtml,
		"assets/html/home.html",
	)
}

func assetsHtmlHomeHtml() (*asset, error) {
	bytes, err := assetsHtmlHomeHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/html/home.html", size: 1343, mode: os.FileMode(420), modTime: time.Unix(1515535819, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _assetsHtmlLayoutHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x52\x3d\x8f\xdb\x30\x0c\xdd\xf3\x2b\x58\xcd\xb5\x74\x06\x8a\xb6\x28\xe4\x1b\xfa\xb1\xb6\x1d\x6e\xe9\x48\x4b\x34\xac\xab\x3e\x02\x93\x71\x2e\x30\xfc\xdf\x0b\xdb\xf1\xe5\x32\x76\x32\x1f\x1f\xe9\xf7\x48\x6a\x9a\xc0\x53\x17\x32\x81\x8a\x78\x29\x27\x51\x30\xcf\x87\x83\x7d\xf7\xfd\xd7\xb7\xa7\x3f\xbf\x7f\x40\x2f\x29\x3e\x1e\xec\xf6\x01\xb0\x3d\xa1\x5f\x02\x00\x9b\x48\x10\x5c\x8f\x03\x93\x34\xea\x24\x5d\xf5\x59\xbd\xa5\x32\x26\x6a\xd4\x18\xe8\x7c\x2c\x83\x28\x70\x25\x0b\x65\x69\xd4\x39\x78\xe9\x1b\x4f\x63\x70\x54\xad\xe0\x3d\x84\x1c\x24\x60\xac\xd8\x61\xa4\xa6\xde\x7f\x24\x41\x22\x3d\x4e\x13\xe8\xa7\x25\x82\x79\xb6\x66\xcb\x6d\x7c\x0c\xf9\x2f\x0c\x14\x1b\xc5\x72\x89\xc4\x3d\x91\x28\xe8\x07\xea\x1a\xd5\x8b\x1c\xf9\x8b\x31\x09\x5f\x9c\xcf\xba\x2d\x45\x58\x06\x3c\x2e\xc0\x95\x64\xba\x92\xa5\xc2\x33\x71\x49\x64\x3e\xe8\x4f\xfa\xc1\x38\xe6\xbb\xb4\x4e\x21\x6b\xc7\xac\xfe\x43\xce\xf9\xfc\xcc\xda\xc5\x72\xf2\x5d\xc4\x81\x56\x2d\x7c\xc6\x17\x13\x43\xcb\xa6\x3d\xc5\x84\xe6\x41\x7f\xd4\xf5\x2a\xb7\xe2\x3b\x1d\x6b\xf6\x25\xdb\xb6\xf8\xcb\x26\x3d\x4d\x20\x94\x8e\x11\x85\x40\x65\x1c\x5b\x1c\x14\xe8\x9f\x6b\x30\xcf\x9b\x3b\x26\x27\xa1\x64\x70\x11\x99\x1b\x75\x85\x57\xef\x00\xd6\x87\x71\xe7\x96\x5b\x60\xc8\x34\xbc\xb2\xcb\x6d\xeb\x9d\x5e\x57\x0c\x81\xab\xfa\x0d\xbf\x9a\x78\xbd\xc3\xad\xcd\xf4\xf5\xad\x68\x29\xf9\x5a\xfc\xe5\x56\x61\x8d\x0f\xe3\x75\x7f\xe6\xea\x69\x1b\x73\x9b\xce\x9a\xed\x71\x1d\xa6\x09\x28\xfb\xa5\xf1\x5f\x00\x00\x00\xff\xff\xea\x52\x8f\x1d\x96\x02\x00\x00")

func assetsHtmlLayoutHtmlBytes() ([]byte, error) {
	return bindataRead(
		_assetsHtmlLayoutHtml,
		"assets/html/layout.html",
	)
}

func assetsHtmlLayoutHtml() (*asset, error) {
	bytes, err := assetsHtmlLayoutHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/html/layout.html", size: 662, mode: os.FileMode(420), modTime: time.Unix(1515259251, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _assetsHtmlNavbarHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x5c\x90\x41\x6a\xc3\x30\x10\x45\xf7\x39\xc5\x47\x7b\x55\x64\x2f\xfb\x08\xbd\xc3\x77\x34\xa9\x86\xca\x63\x90\x85\x5b\x10\xbe\x7b\xa9\xeb\x86\x36\xdb\xf7\x86\xc7\x67\x7a\x47\x92\xbb\x9a\xc0\x19\xb7\x89\xd5\x61\xdf\x2f\xd1\xb8\xe1\x56\xb8\xae\xc3\x89\xa1\xab\x4f\xac\xef\x0e\x75\x29\x72\x50\x7d\x63\xd3\xc5\x1c\x58\x95\xbe\x70\x92\x32\xb8\x99\x6a\xf8\x23\xc7\x0b\x10\x93\x3e\xd5\xfc\x54\x69\xe9\x90\x40\xe4\x93\xd4\x26\xb3\x43\xae\x72\x1f\x5c\x38\x8f\xfe\x57\x6e\x8b\x35\xaa\x49\x7d\x58\x20\xe6\xeb\xaf\x6e\xda\x8a\x20\x73\xf5\x4d\x3e\x9b\xff\xc8\xda\xc4\x8d\xbd\xe3\xe5\x95\xb3\x60\xdf\x63\xc8\xd7\x47\x37\x24\xdd\xce\x25\x81\xc7\xde\x1f\x12\x83\x71\x1b\x2f\xbd\x43\x2c\x7d\x7f\xe5\x2b\x00\x00\xff\xff\x14\x37\x64\x2c\x2c\x01\x00\x00")

func assetsHtmlNavbarHtmlBytes() ([]byte, error) {
	return bindataRead(
		_assetsHtmlNavbarHtml,
		"assets/html/navbar.html",
	)
}

func assetsHtmlNavbarHtml() (*asset, error) {
	bytes, err := assetsHtmlNavbarHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/html/navbar.html", size: 300, mode: os.FileMode(420), modTime: time.Unix(1515255194, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"assets/html/home.html": assetsHtmlHomeHtml,
	"assets/html/layout.html": assetsHtmlLayoutHtml,
	"assets/html/navbar.html": assetsHtmlNavbarHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"assets": &bintree{nil, map[string]*bintree{
		"html": &bintree{nil, map[string]*bintree{
			"home.html": &bintree{assetsHtmlHomeHtml, map[string]*bintree{}},
			"layout.html": &bintree{assetsHtmlLayoutHtml, map[string]*bintree{}},
			"navbar.html": &bintree{assetsHtmlNavbarHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

